data:
  seed: 42

checkpoint:
  # path: 'pretrained_ckpt/all_models/whisper_mfcc_mesonet/weights.pth'
  path: 'out_ckpt/model_epoch_1.pth'
  

model:
  name: whisper_frontend_mesonet
  optimizer:
    lr: 1.0e-06
    weight_decay: 0.0001
  parameters:
    fc1_dim: 1024
    freeze_encoder: false
    frontend_algorithm: ["mfcc"]
    input_channels: 2
